# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 446)
        MainWindow.setStyleSheet("background-image: url( C:\\Users\\Artem\\PycharmProjects\\mathgame\\img.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(20)
        self.head.setFont(font)
        self.head.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.head.setAlignment(QtCore.Qt.AlignCenter)
        self.head.setObjectName("head")
        self.verticalLayout.addWidget(self.head)
        spacerItem = QtWidgets.QSpacerItem(500, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout.setSpacing(70)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Ready = QtWidgets.QPushButton(self.centralwidget)
        self.Ready.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Ready.setFont(font)
        self.Ready.setStyleSheet("QPushButton{\n"
"    color: #a32a2a ;\n"
"    background-color: #321e3b;\n"
"    border: #de1b1b;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #f0b92e ;\n"
"    background-color: #878433;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #f05513;\n"
"}")
        self.Ready.setFlat(False)
        self.Ready.setObjectName("Ready")
        self.horizontalLayout.addWidget(self.Ready)
        self.test = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.test.setFont(font)
        self.test.setAutoFillBackground(False)
        self.test.setStyleSheet("QPushButton{\n"
"    color: #a32a2a ;\n"
"    background-color: #321e3b;\n"
"    border: #de1b1b;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #f0b92e ;\n"
"    background-color: #878433;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #f05513;\n"
"}")
        self.test.setObjectName("test")
        self.horizontalLayout.addWidget(self.test)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.head.setText(_translate("MainWindow", "Выберите действие"))
        self.Ready.setText(_translate("MainWindow", "Подготовится"))
        self.test.setText(_translate("MainWindow", "Пройти тест"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
