# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'povtor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_povtor(object):
    def setupUi(self, povtor):
        povtor.setObjectName("povtor")
        povtor.resize(347, 382)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(povtor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.logar = QtWidgets.QPushButton(povtor)
        self.logar.setObjectName("logar")
        self.verticalLayout.addWidget(self.logar)
        self.trig = QtWidgets.QPushButton(povtor)
        self.trig.setObjectName("trig")
        self.verticalLayout.addWidget(self.trig)
        self.Nerav = QtWidgets.QPushButton(povtor)
        self.Nerav.setObjectName("Nerav")
        self.verticalLayout.addWidget(self.Nerav)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.menub = QtWidgets.QPushButton(povtor)
        self.menub.setObjectName("menub")
        self.verticalLayout_2.addWidget(self.menub)

        self.retranslateUi(povtor)
        QtCore.QMetaObject.connectSlotsByName(povtor)

    def retranslateUi(self, povtor):
        _translate = QtCore.QCoreApplication.translate
        povtor.setWindowTitle(_translate("povtor", "Form"))
        self.logar.setText(_translate("povtor", "Логарифмы"))
        self.trig.setText(_translate("povtor", "Тригонометрия"))
        self.Nerav.setText(_translate("povtor", "Неравенства"))
        self.menub.setText(_translate("povtor", "Главное меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    povtor = QtWidgets.QWidget()
    ui = Ui_povtor()
    ui.setupUi(povtor)
    povtor.show()
    sys.exit(app.exec_())
