# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Artem\PycharmProjects\mathgame\w3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 316)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 20, 241, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.trigan = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.trigan.setObjectName("trigan")
        self.verticalLayout.addWidget(self.trigan)
        self.logar1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.logar1.setObjectName("logar1")
        self.verticalLayout.addWidget(self.logar1)
        self.nerav = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.nerav.setObjectName("nerav")
        self.verticalLayout.addWidget(self.nerav)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.munubut = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.munubut.setObjectName("munubut")
        self.verticalLayout_2.addWidget(self.munubut)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Выберите ваш класс"))
        self.trigan.setText(_translate("Form", "Тригонометрия"))
        self.logar1.setText(_translate("Form", "Логарифмы"))
        self.nerav.setText(_translate("Form", "Неравенства"))
        self.munubut.setText(_translate("Form", "Вернуться в главное меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
